---

- name: DOWNLOAD GPG KEY
  get_url:
    url: https://packages.sury.org/php/apt.gpg
    dest: /etc/apt/trusted.gpg.d/php.gpg

- name: INSTALLING NEW REPOS
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: APT UPDATE
  apt:
    update_cache: true
    force_apt_get: true

- name: INSTALLING PHP8.0 PACKAGES
  apt:
    pkg: 
      - php8.0 
      - php8.0-fpm 
      - php8.0-mysql 
      - php8.0-pgsql 
      - php8.0-sqlite3 
      - php8.0-bcmath 
      - php8.0-mbstring 
      - php8.0-xml 
      - php8.0-curl 
      - php8.0-zip 
      - php8.0-gd
      - libapache2-mod-php8.0

- name: Downloading Azuriom CMS.
  get_url:
    url: https://azuriom.s3.fr-par.scw.cloud/AzuriomInstaller.zip
    dest: /var/www/

- name: Create azuriom folder
  file:
    path: /var/www/azuriom
    state: directory

- name: Unziping Azuriom.
  unarchive:
    src: /var/www/AzuriomInstaller.zip
    dest: /var/www/azuriom
    remote_src: yes

- name: Folder Permission
  file: 
    path: /var/www/azuriom
    state: directory 
    recurse: yes
    owner: www-data
    group: www-data
    
- name: Add crontab for scheduler
  cron:
    job: cd /var/www/azuriom && php artisan schedule:run >> /dev/null 2>&1

- name: Copy vHost
  template: src=../files/azuriom.conf dest=/etc/apache2/sites-enabled/000-default.conf

- name: enable rewrite module
  shell: a2enmod rewrite

- name: restart apache2
  service: name=apache2 state=restarted