---

- hosts: bungee
  roles:
    - default
    - bungee
  remote_user: root
  vars_files:
    - var.yaml

- hosts: server
  roles:
    - default
    - serveur
  remote_user: root
  vars_files:
    - var.yaml
  tasks:
  - pause: 
      seconds: 1
      prompt: |
        /////////////////
        {{post_install}}
        /////////////////  